### ISSUE TITLE
convergence issue

### ISSUE THREAD

**Issue by fkrauer** [itsdfish/DifferentialEvolutionMCMC.jl#29] opened 2021-05-06 10:34 UTC
Hei

I am running your example with 10,000 iterations and no burn-in. I fit it repeatedly and noticed that occasionally, some chains converge only after several thousands of iterations. I have added one example. The burn-in of 1000 and iterations of 2000 in your example would thus be way to few. Is this something to be worried about? Thanks, Fabienne
![example](https://user-images.githubusercontent.com/36159611/117284654-5cfed080-ae67-11eb-825d-81794f3252f4.png)

**Comment by itsdfish** [comment] 2021-05-07 08:30
Hi. Would you mind sharing the code for your example so I can investigate? I suspect there might be rare occasions in which a chain does not converge, but I would need to see your code to understand better.

**Comment by itsdfish** [comment] 2021-05-07 11:21
@fkrauer, 

I suspect that part of the issue is that the crossover function works differently during the burin phase. During burnin, the crossover equation includes a term that biases the proposal towards the current particle with the maximum posterior log likelihood. This modification of the original crossover function was designed to mitigate the issue that you reported. After the burnin phase, the original crossover equation is used. Otherwise, the mode will be oversampled. 

In VSCode, I ran the following code at the bottom of the Gaussian Example:

```
for i in 1:100
    Random.seed!(i)
    data = rand(Normal(0.0, 1.0), 50)
    model = DEModel(; priors, model=loglike, data)

    de = DE(;bounds, burnin=1000, priors)
    n_iter = 10_000
    chains = sample(model, de, MCMCThreads(), n_iter, progress=true)
    display(plot(chains))
    println("seed ", i)
end
```

I did not identify any anomalies after scanning through the plots. I suspect that one could encounter an anomaly  given a sufficiently large number of repetitions. In general, the best practice is to inspect rhat and the trace plot on a case-by-case basis. Although DifferentialEvolutionMCMC is not as efficient as NUTS, it seems like it is performing as expected when burnin > 0.

**Comment by itsdfish** [comment] 2021-05-07 11:36
I can also verify that there is at least one "rogue" chain every eight or so replications when burnin = 0. All in all, this demonstrates the advantage of using the modified crossover equation during the burnin phase. Also, I suspect the sheer number of particles is a contributing factor. There are four groups of six particles, totalling 24. Having a large number of particles increases the chance of at least one anomaly on a given run. 

Thanks for reporting. Its good to have a second pair of eyes. I will close the issue for now. Please feel free to reopen if you encounter any unexpected behavior.

**Closed as completed by itsdfish** 2021-05-07 11:36 UTC

**Comment by fkrauer** [comment] 2021-05-08 09:26
thanks for the explanation. I find it challenging to determine the burn-in beforehand. I can't possibly know in advance how many iterations it will take to convergence. I used to work in R with the BayesianTools package (includes also a DE MCMC), where the burn-in is determined and discarded AFTER running and inspection of the chains. I thought that was more intuitive. But maybe I am missing a point here. Thanks anyway

**Comment by itsdfish** [comment] 2021-05-08 10:14
No problem. Determining the right burnin setting is challenging. Generally speaking, the modified crossover will allow you to select a lower number. However, you can set burnin = 0 so that it functions like BayesianTools and you can manually remove burnin post hoc with subsetting.

**Comment by itsdfish** [comment] 2021-05-10 10:25
@fkrauer,

By the way, I added the ability to retain burnin samples with the keyword `discard_burnin=false` for the sampler object. In practice, I think you will ultimately discard the burnin samples because the variance is underestimated. In any case, this should give you the ability to inspect the burnin samples and discard samples as you see fit. This new feature should be available sometime today.
